quicc_target_sources(${QUICC_CURRENT_COMPONENT_LIB} ${QUICC_CMAKE_SRC_VISIBILITY}
  FieldProbeWriter.cpp
  ICartesian1DScalarEnergyBaseWriter.cpp
  ICartesian1DScalarEnergyWriter.cpp
  ICartesian1DTorPolEnergyBaseWriter.cpp
  ICartesian1DTorPolEnergyWriter.cpp
  Cartesian1DScalarEnergyWriter.cpp
  Cartesian1DTorPolEnergyWriter.cpp
  ISphericalScalarEnergyBaseWriter.cpp
  ISphericalScalarEnergyWriter.cpp
  ISphericalScalarLSpectrumWriter.cpp
  ISphericalScalarMSpectrumWriter.cpp
  ISphericalScalarModeSpectrumWriter.cpp
  ISphericalScalarNSpectrumWriter.cpp
  ISphericalScalarRSpectrumWriter.cpp
  ISphericalScalarPowerBaseWriter.cpp
  ISphericalTorPolEnergyBaseWriter.cpp
  ISphericalTorPolEnergyWriter.cpp
  ISphericalTorPolLSpectrumWriter.cpp
  ISphericalTorPolMSpectrumWriter.cpp
  ISphericalTorPolModeSpectrumWriter.cpp
  ISphericalTorPolNScalarSpectrumWriter.cpp
  ISphericalTorPolNSpectrumWriter.cpp
  ISphericalTorPolRSpectrumWriter.cpp
  ISphericalTorPolPowerBaseWriter.cpp
  ISphericalTorPolScalarSpectrumBaseWriter.cpp
  ISphericalTorPolEnstrophyBaseWriter.cpp
  ISphericalTorPolEnstrophyWriter.cpp
  ISphericalTorPolEnstrophyLSpectrumWriter.cpp
  ISphericalTorPolEnstrophyMSpectrumWriter.cpp
  IVariableAsciiWriter.cpp
  IVariableHdf5NWriter.cpp
  IVariableHdf5Reader.cpp
  ShellAngularMomentumWriter.cpp
  ShellNusseltWriter.cpp
  ShellDipolarityWriter.cpp
  ShellLuminosityWriter.cpp
  ShellRadialProfilesWriter.cpp
  ShellScalarEnergyWriter.cpp
  ShellScalarNSpectrumWriter.cpp
  ShellScalarLSpectrumWriter.cpp
  ShellScalarMSpectrumWriter.cpp
  ShellScalarModeSpectrumWriter.cpp
  ShellScalarRSpectrumWriter.cpp
  ShellTorPolEnergyWriter.cpp
  ShellTorPolNScalarSpectrumWriter.cpp
  ShellTorPolLSpectrumWriter.cpp
  ShellTorPolMSpectrumWriter.cpp
  ShellTorPolModeSpectrumWriter.cpp
  ShellTorPolRSpectrumWriter.cpp
  ShellTorPolEnstrophyWriter.cpp
  ShellTorPolEnstrophyLSpectrumWriter.cpp
  ShellTorPolEnstrophyMSpectrumWriter.cpp
  SphereAngularMomentumWriter.cpp
  SphereDipolarityWriter.cpp
  SphereMaxAbsoluteFieldValueWriter.cpp
  SphereNusseltWriter.cpp
  SphereRadialProfilesWriter.cpp
  SphereScalarMeanWriter.cpp
  SphereScalarEnergyWriter.cpp
  SphereScalarLSpectrumWriter.cpp
  SphereScalarMSpectrumWriter.cpp
  SphereScalarModeSpectrumWriter.cpp
  SphereScalarNSpectrumWriter.cpp
  SphereScalarRSpectrumWriter.cpp
  SphereTorPolEnergyWriter.cpp
  SphereTorPolNScalarSpectrumWriter.cpp
  SphereTorPolLSpectrumWriter.cpp
  SphereTorPolMSpectrumWriter.cpp
  SphereTorPolModeSpectrumWriter.cpp
  SphereTorPolNSpectrumWriter.cpp
  SphereTorPolRSpectrumWriter.cpp
  SphereTorPolEnstrophyWriter.cpp
  SphereTorPolEnstrophyLSpectrumWriter.cpp
  SphereTorPolEnstrophyMSpectrumWriter.cpp
  StateFileReader.cpp
  StateFileWriter.cpp
  VisualizationFileReader.cpp
  VisualizationFileWriter.cpp
  )

add_subdirectory(Tags)
