.cscs_x86_64_builder:
  extends: .container-builder-cscs-zen2

.cscs_aarch64_builder:
  extends: .container-builder-cscs-gh200

.alps-a100_builder:
  extends: .cscs_x86_64_builder

.alps-gh200_builder:
  extends: .cscs_aarch64_builder

.alps-zen2_builder:
  extends: .cscs_x86_64_builder
