FROM ubuntu:20.04

MAINTAINER Andreas Fink <andreas.fink@cscs.ch>

ARG SPACK_VER=0.17.0
ENV SPACK_ROOT=/opt/spack

# This list corresponds mostly to the list from the spack dockerfile (share/spack/docker/ubuntu-1804.dockerfile)
RUN apt-get update \
  && env DEBIAN_FRONTEND=noninteractive TZ=Europe/Zurich \
  apt-get -yqq install --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    file \
    g++ \
    gcc \
    gfortran \
    git \
    gnupg2 \
    iproute2 \
    lmod \
    locales \
    lua-posix \
    make \
    patch \
    python3 \
    python3-pip \
    python3-setuptools \
    tcl \
    unzip \
    vim \
    less \
  && locale-gen en_US.UTF-8 \
  && rm -Rf /var/lib/apt/lists/*

RUN mkdir -p $SPACK_ROOT \
  && git clone -b v${SPACK_VER} https://github.com/spack/spack $SPACK_ROOT \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/docker-shell \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/interactive-shell \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/spack-env

ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN mkdir -p /root/.spack \
 && cp $SPACK_ROOT/share/spack/docker/modules.yaml /root/.spack/modules.yaml \
 && rm -rf /root/*.* /run/nologin $SPACK_ROOT/.git

WORKDIR /root
SHELL ["docker-shell"]

RUN spack spec hdf5+mpi
ENTRYPOINT ["/bin/bash", "/opt/spack/share/spack/docker/entrypoint.bash"]
CMD ["interactive-shell"]

