# Create component library
set(QUICC_CURRENT_SUBCOMPONENT_LIB ${QUICC_CURRENT_COMPONENT_LIB}_FiniteDiff)
set(QUICC_CURRENT_SUBSUBCOMPONENT_LIB Sphere)
add_library(${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB} INTERFACE "")

target_include_directories(${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
  INTERFACE
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../../..>"
    "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
)

# Add public header
set(PHS
  Builder.hpp
)

set_target_properties(${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
  PROPERTIES
    PUBLIC_HEADER "${PHS}"
)

target_link_libraries(${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
  INTERFACE
    QuICC::Std
    QuICC::View
    QuICC::Profiling
    QuICC::Memory
    QuICC::SparseOp
    QuICC::FiniteDiff
    QuICC::ViewOps::Quadrature
    QuICC::ViewOps::Pointwise
    QuICC::ViewOps::Reduction
)


# Alias
add_library(${QUICC_NAMESPACE}${QUICC_CURRENT_COMPONENT_LIB_NAMESPACE}FiniteDiff::${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
  ALIAS ${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB})

# Export info
quicc_export_target(${QUICC_CURRENT_SUBCOMPONENT_LIB}_${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
  COMPONENT ${QUICC_CURRENT_COMPONENT_LIB_NAMESPACE}FiniteDiff::${QUICC_CURRENT_SUBSUBCOMPONENT_LIB}
)

