quicc_target_sources(${QUICC_CURRENT_COMPONENT_LIB} ${QUICC_CMAKE_SRC_VISIBILITY}
  IDiags.cpp
  Id.cpp
  IdDiags.cpp
  I2.cpp
  I2Diags.cpp
  I2Lapl.cpp
  I2LaplDiags.cpp
  I2Qp.cpp
  I2QpDiags.cpp
  I2Qm.cpp
  I2QmDiags.cpp
  I3.cpp
  I3Diags.cpp
  I3Lapl.cpp
  I3LaplDiags.cpp
  I3Qm.cpp
  I3QmDiags.cpp
  I3Qp.cpp
  I3QpDiags.cpp
  I3D2p.cpp
  I3D2pDiags.cpp
  I4.cpp
  I4Diags.cpp
  I4D1R1.cpp
  I4D1R1Diags.cpp
  I4Lapl.cpp
  I4LaplDiags.cpp
  I4Lapl2.cpp
  I4Lapl2Diags.cpp
  I4Qm.cpp
  I4QmDiags.cpp
  I4Qp.cpp
  I4QpDiags.cpp
  I4D2p.cpp
  I4D2pDiags.cpp
  I6.cpp
  I6Diags.cpp
  I6CylLaplh.cpp
  I6CylLaplhDiags.cpp
  R2.cpp
  R2Diags.cpp
  Tools.cpp
)

add_subdirectory(Boundary)
add_subdirectory(Chebyshev)
add_subdirectory(Legendre)
add_subdirectory(CylEnergy)
add_subdirectory(SphEnergy)
add_subdirectory(Stencil)
