import sympy as sy

n = sy.Symbol('N')
a = sy.Symbol('a')
b = sy.Symbol('b')

print("Natural normalization of Jacobi polynomials")
print("===========================================")
# General Pn
Pnc0 = -(n+a-1)*(n+b-1)*(2*n+a+b)/(n*(n+a+b)*(2*n+a+b-2))
Pnc1 = (2*n+a+b-1)*(2*n+a+b)/(2*n*(n+a+b))
Pnc2 = (a*a - b*b)*(2*n+a+b-1)/(2*n*(n+a+b)*(2*n+a+b-2))
Pnc3 = 1
# P1
P1c0 = (a+b+2)
P1c1 = (a-b)
P1c2 = sy.Rational(1,2)
# P0
P0c0 = 1
print("Polynomial recurrence:")
print(Pnc0.simplify().factor())
print(Pnc1.simplify().factor())
print(Pnc2.simplify().factor())
print(Pnc3)
print("Polynomial n = 1 recurrence:")
print(P1c0.simplify().factor())
print(P1c1.simplify().factor())
print(P1c2.simplify().factor())
print("Polynomial n = 0 recurrence:")
print(P0c0)
print("-------------------------------------------")
# General DPn
DPnc0 = (n+a+b)*Pnc0*Pnc3/(n+a+b-2)
DPnc1 = (n+a+b)*Pnc1*Pnc3/(n+a+b-1)
DPnc2 = (n+a+b)*Pnc2*Pnc3/(n+a+b-1)
DPnc3 = 1/(n+a+b-1)
# DP1
DP1c0 = (a+b+1)*P1c0*P1c2/(a+b)
DP1c1 = (a+b+1)*P1c1*P1c2/(a+b)
DP1c2 = (a+b+1)/(2*(a+b))
# DP0
DP0c0 = sy.Rational(1,2)*(a+b)
print("First derivative recurrence:")
print((DPnc0/DPnc3).simplify().factor())
print((DPnc1/DPnc3).simplify().factor())
print((DPnc2/DPnc3).simplify().factor())
print(DPnc3)
print("First derivative n = 1 recurrence:")
print((DP1c0/DP1c2).simplify().factor())
print((DP1c1/DP1c2).simplify().factor())
print(DP1c2.simplify().factor())
print("First derivative n = 0 recurrence:")
print(DP0c0.simplify().factor())
print("-------------------------------------------")
# General D2Pn
D2Pnc0 = (n+a+b)*(n+a+b-1)*Pnc0*Pnc3/((n+a+b-2)*(n+a+b-3))
D2Pnc1 = (n+a+b)*(n+a+b-1)*Pnc1*Pnc3/((n+a+b-1)*(n+a+b-2))
D2Pnc2 = (n+a+b)*(n+a+b-1)*Pnc2*Pnc3/((n+a+b-1)*(n+a+b-2))
D2Pnc3 = 1/(n+a+b-2)
# P1
D2P1c0 = (a+b+1)*(a+b)*P1c0*P1c2/((a+b)*(a+b-1))
D2P1c1 = (a+b+1)*(a+b)*P1c1*P1c2/((a+b)*(a+b-1))
D2P1c2 = (a+b+1)/(2*(a+b-1))
# P0
D2P0c0 = sy.Rational(1,4)*(a+b)*(a+b-1)
print("Second derivative recurrence:")
print((D2Pnc0/D2Pnc3).simplify().factor())
print((D2Pnc1/D2Pnc3).simplify().factor())
print((D2Pnc2/D2Pnc3).simplify().factor())
print(D2Pnc3)
print("Second derivative n = 1 recurrence:")
print((D2P1c0/D2P1c2).simplify().factor())
print((D2P1c1/D2P1c2).simplify().factor())
print(D2P1c2.simplify().factor())
print("Second derivative n = 0 recurrence:")
print(D2P0c0.simplify().factor())
print("-------------------------------------------")
# General D3Pn
D3Pnc0 = (n+a+b)*(n+a+b-1)*(n+a+b-2)*Pnc0*Pnc3/((n+a+b-2)*(n+a+b-3)*(n+a+b-4))
D3Pnc1 = (n+a+b)*(n+a+b-1)*(n+a+b-2)*Pnc1*Pnc3/((n+a+b-1)*(n+a+b-2)*(n+a+b-3))
D3Pnc2 = (n+a+b)*(n+a+b-1)*(n+a+b-2)*Pnc2*Pnc3/((n+a+b-1)*(n+a+b-2)*(n+a+b-3))
D3Pnc3 = 1/(n+a+b-3)
# P1
D3P1c0 = (a+b+1)*(a+b)*(a+b-1)*P1c0*P1c2/((a+b)*(a+b-1)*(a+b-2))
D3P1c1 = (a+b+1)*(a+b)*(a+b-1)*P1c1*P1c2/((a+b)*(a+b-1)*(a+b-2))
D3P1c2 = (a+b+1)/(2*(a+b-2))
# P0
D3P0c0 = sy.Rational(1,8)*(a+b)*(a+b-1)*(a+b-2)
print("Third derivative recurrence:")
print((D3Pnc0/D3Pnc3).simplify().factor())
print((D3Pnc1/D3Pnc3).simplify().factor())
print((D3Pnc2/D3Pnc3).simplify().factor())
print(D3Pnc3)
print("Third derivative n = 1 recurrence:")
print((D3P1c0/D3P1c2).simplify().factor())
print((D3P1c1/D3P1c2).simplify().factor())
print(D3P1c2.simplify().factor())
print("Third derivative n = 0 recurrence:")
print(D3P0c0.simplify().factor())
print("-------------------------------------------")
