include:
    - remote: https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml

# build_spack_base and build_spack_base2 should be the same stage, but currently the GPU build fails,
# until this is fixed it is moved after the generation of the CPU build, such that CPU baseimage can be updated
stages:
  - build_spack_base
  - build_base

build_baseimage_spack_cpu:
  extends: .container-builder-podman
  stage: build_spack_base
  variables:
    DOCKERFILE: ci/docker/baseimage/Dockerfile_spack_baseimage_cpu
    PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/ubuntu-spack:22.04-0.18.0

build_baseimage_spack_gpu:
  extends: .container-builder-podman
  stage: build_spack_base
  variables:
    DOCKERFILE: ci/docker/baseimage/Dockerfile_spack_baseimage_gpu
    PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/cuda-ubuntu-spack:11.7.1-22.04-0.18.0

build_baseimage_cpu:
    extends: .container-builder-podman
    stage: build_base
    timeout: 8 hours
    variables:
      DOCKERFILE: ci/docker/baseimage/Dockerfile_quicc_baseimage_cpu
      PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/ubuntu-quicc-buildbase:22.04

build_baseimage_gpu:
    extends: .container-builder-podman
    stage: build_base
    timeout: 8 hours
    variables:
      DOCKERFILE: ci/docker/baseimage/Dockerfile_quicc_baseimage_gpu
      PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/cuda-ubuntu-quicc-buildbase:11.7.1-22.04
