.cpu:
  extends: .daint
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    USE_MPI: 'YES'
    SLURM_CONSTRAINT: 'mc'
    SLURM_NNODES: 1
    SLURM_NTASKS_PER_NODE: 1
    SLURM_TIMELIMIT: '20:00'

.gpu:
  extends: .daint
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    USE_MPI: 'YES'
    SLURM_CONSTRAINT: 'gpu'
    SLURM_NNODES: 1
    SLURM_NTASKS_PER_NODE: 1
    SLURM_TIMELIMIT: '20:00'
