build-quicc_mp:
  tags:
    - docker_jfrog # this is a gitlab-runner which runs a `docker build` step
  stage: build
  script:
    # we are using a Dockerfile that contains the real build instructions, this script will be ignored by the docker_jfrog runner if DOCKERFILE is set
    - "true"
  variables:
    DOCKERFILE: docker/Dockerfile_mp
    PERSIST_IMAGE_NAME: quicc_mp:latest # only lowercase letters are allowed!

include:
  - /ci/.daint_runner.yml

test-quicc_mp-lib:
  extends:
    - .cpu
  # TODO: hide the implementation detail for the full URL of the image
  image: art.cscs.ch/contbuild/testing/anfink/quicc_mp:latest
  script:
    # the tests are not installed, so we need to run them from the build directory
    - cd /QuICC.src/build
    - ctest --no-tests=error --output-on-failure -R PolynomialQuadratureTests_
    - ctest --no-tests=error --output-on-failure -R PolynomialWorlandTests_
    - ctest --no-tests=error --output-on-failure -R PolynomialALegendreTests_
    - ctest --no-tests=error --output-on-failure -R "TransformWorlandTests_Poly_D1_.*projector"
    - ctest --no-tests=error --output-on-failure -R "TransformWorlandTests_.*_integrator"
    - ctest --no-tests=error --output-on-failure -R "TransformWorlandTests_.*_reductor"
    - ctest --no-tests=error --output-on-failure -R "TransformWorlandTests_.*_bfloop"
    - ctest --no-tests=error --output-on-failure -R FrameworkLoadSplitterTests_
