if(HDF5_FOUND)
  message(STATUS "HDF5 VERSION: ${HDF5_VERSION}")
  if(NOT HDF5_VERSION_MINOR)
    string(REPLACE "." ";" _version ${HDF5_VERSION})
    list(GET _version 1 HDF5_VERSION_MINOR)
  endif()
  if(HDF5_VERSION_MINOR GREATER_EQUAL 14)
    target_compile_definitions(${QUICC_CURRENT_COMPONENT_LIB} PUBLIC "QUICC_HDF5_V14_HSIZE_T")
  endif()
endif()
