if(HDF5_FOUND)
  message(STATUS "HDF5 VERSION: ${HDF5_VERSION}")
  string(REPLACE "." ";" _version ${HDF5_VERSION})
  list(GET _version 1 _minor_version)
  message(VERBOSE "HDF5 MINOR VERSION: ${_minor_version}")
  if(_minor_version GREATER_EQUAL 14)
    target_compile_definitions(${QUICC_CURRENT_COMPONENT_LIB} PUBLIC "QUICC_HDF5_V14_HSIZE_T")
  endif()
endif()
